// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantPlatform.Infrastructure.Data;

#nullable disable

namespace RestaurantPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616204033_SeedCategoriesandMenudata")]
    partial class SeedCategoriesandMenudata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SelectedOptions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Dosa"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Biryani & Pulao"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Idly"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Uttapam Spcls"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Curries"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "Indian Bread"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            IsActive = true,
                            Name = "Appetizers - Veg"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            IsActive = true,
                            Name = "Appetizers - Non Veg"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            IsActive = true,
                            Name = "Fried Rice / Noodles"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Frankie's"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            IsActive = true,
                            Name = "South Indian Spcl Snacks"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            IsActive = true,
                            Name = "Mandi"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            IsActive = true,
                            Name = "Drinks"
                        });
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.ItemOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ExtraPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.ToTable("ItemOptions");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVeg")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SpiceLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Crisp rice and lentil crepe.",
                            DisplayOrder = 1,
                            ImageUrl = "/images/menu/plain-dosa.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Plain Dosa",
                            Price = 6.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Dosa filled with spiced potato masala.",
                            DisplayOrder = 2,
                            ImageUrl = "/images/menu/masala-dosa.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Masala Dosa",
                            Price = 6.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Dosa roasted in clarified butter.",
                            DisplayOrder = 3,
                            ImageUrl = "/images/menu/ghee-dosa.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Ghee Dosa",
                            Price = 7.49m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Crisp semolina dosa with onions and green chili.",
                            DisplayOrder = 4,
                            ImageUrl = "/images/menu/rava-dosa.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Onion Rava Dosa",
                            Price = 8.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Spicy Vijayawada style chicken biryani.",
                            DisplayOrder = 1,
                            ImageUrl = "/images/menu/vijayawada-biryani.jpg",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Vijayawada Biryani",
                            Price = 17.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Basmati rice with seasonal vegetables and spices.",
                            DisplayOrder = 2,
                            ImageUrl = "/images/menu/veg-biryani.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Veg Dum Biryani",
                            Price = 14.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Slow-cooked layered chicken biryani.",
                            DisplayOrder = 3,
                            ImageUrl = "/images/menu/chicken-biryani.jpg",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Chicken Dum Biryani",
                            Price = 16.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Fragrant rice tossed with paneer and spices.",
                            DisplayOrder = 4,
                            ImageUrl = "/images/menu/paneer-pulao.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Paneer Pulao",
                            Price = 14.49m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Two steamed rice cakes with chutney and sambar.",
                            DisplayOrder = 1,
                            ImageUrl = "/images/menu/plain-idly.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Plain Idly",
                            Price = 4.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Idly tossed in ghee and spicy podi.",
                            DisplayOrder = 2,
                            ImageUrl = "/images/menu/karam-idly.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Ghee Karam Idly",
                            Price = 6.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "Thick savory pancake.",
                            DisplayOrder = 1,
                            ImageUrl = "/images/menu/plain-uttapam.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Plain Uttapam",
                            Price = 6.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "Uttapam topped with onions and chili.",
                            DisplayOrder = 2,
                            ImageUrl = "/images/menu/onion-uttapam.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Onion Uttapam",
                            Price = 7.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Description = "Paneer in a rich tomato butter gravy.",
                            DisplayOrder = 1,
                            ImageUrl = "/images/menu/paneer-butter-masala.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Paneer Butter Masala",
                            Price = 13.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "Home-style chicken curry.",
                            DisplayOrder = 2,
                            ImageUrl = "/images/menu/chicken-curry.jpg",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Chicken Curry",
                            Price = 14.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            Description = "Thin handkerchief bread served with curry.",
                            DisplayOrder = 1,
                            ImageUrl = "/images/menu/rumali-roti.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Rumali Roti with Curry",
                            Price = 9.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            Description = "Tandoor-baked naan brushed with butter.",
                            DisplayOrder = 2,
                            ImageUrl = "/images/menu/butter-naan.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Butter Naan",
                            Price = 3.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 7,
                            Description = "Crispy cauliflower in tangy Manchurian sauce.",
                            DisplayOrder = 1,
                            ImageUrl = "/images/menu/gobi-manchurian.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Gobi Manchurian",
                            Price = 11.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 7,
                            Description = "Two pastry pockets with spiced potato.",
                            DisplayOrder = 2,
                            ImageUrl = "/images/menu/samosa.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Punjabi Samosa",
                            Price = 3.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 8,
                            Description = "Spicy deep-fried chicken bites.",
                            DisplayOrder = 1,
                            ImageUrl = "/images/menu/chicken-65.jpg",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Chicken 65",
                            Price = 13.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 8,
                            Description = "Crispy fried fish tossed in chili and curry leaf.",
                            DisplayOrder = 2,
                            ImageUrl = "/images/menu/apollo-fish.jpg",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Apollo Fish",
                            Price = 15.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 9,
                            Description = "Wok-tossed street style noodles.",
                            DisplayOrder = 1,
                            ImageUrl = "/images/menu/fried-noodles.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Street Style Fried Noodles",
                            Price = 14.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 9,
                            Description = "Indian street style chicken fried rice.",
                            DisplayOrder = 2,
                            ImageUrl = "/images/menu/chicken-fried-rice.jpg",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Chicken Fried Rice",
                            Price = 14.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 10,
                            Description = "Roll stuffed with spiced paneer.",
                            DisplayOrder = 1,
                            ImageUrl = "/images/menu/paneer-frankie.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Paneer Frankie",
                            Price = 9.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 10,
                            Description = "Roll stuffed with spiced chicken.",
                            DisplayOrder = 2,
                            ImageUrl = "/images/menu/chicken-frankie.jpg",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Chicken Frankie",
                            Price = 10.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 11,
                            Description = "Ghee and spice tossed fried fritters.",
                            DisplayOrder = 1,
                            ImageUrl = "/images/menu/punugulu.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Neyyi Karam Punugulu",
                            Price = 10.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 11,
                            Description = "Soft fried lentil dumplings.",
                            DisplayOrder = 2,
                            ImageUrl = "/images/menu/mysore-bonda.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Mysore Bonda",
                            Price = 9.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 12,
                            Description = "Smoky spiced rice with chicken, Yemeni style.",
                            DisplayOrder = 1,
                            ImageUrl = "/images/menu/chicken-mandi.jpg",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Chicken Mandi",
                            Price = 18.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 13,
                            Description = "Signature sweet milky tea.",
                            DisplayOrder = 1,
                            ImageUrl = "/images/menu/irani-chai.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Irani Chai",
                            Price = 2.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 13,
                            Description = "Chilled yogurt and mango drink.",
                            DisplayOrder = 2,
                            ImageUrl = "/images/menu/mango-lassi.jpg",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Mango Lassi",
                            Price = 4.99m,
                            SpiceLevel = 0
                        });
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.OperatingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time");

                    b.Property<int>("RestaurantInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantInfoId");

                    b.ToTable("OperatingHours");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Tax")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SelectedOptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartySize")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.RestaurantInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Lng")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RestaurantInfos");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.Cart", b =>
                {
                    b.HasOne("RestaurantPlatform.Domain.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("RestaurantPlatform.Domain.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("RestaurantPlatform.Domain.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantPlatform.Domain.Entities.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.ItemOption", b =>
                {
                    b.HasOne("RestaurantPlatform.Domain.Entities.MenuItem", "MenuItem")
                        .WithMany("Options")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.MenuItem", b =>
                {
                    b.HasOne("RestaurantPlatform.Domain.Entities.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.OperatingHours", b =>
                {
                    b.HasOne("RestaurantPlatform.Domain.Entities.RestaurantInfo", "RestaurantInfo")
                        .WithMany("Hours")
                        .HasForeignKey("RestaurantInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RestaurantInfo");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.Order", b =>
                {
                    b.HasOne("RestaurantPlatform.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("RestaurantPlatform.Domain.Entities.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantPlatform.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.Payment", b =>
                {
                    b.HasOne("RestaurantPlatform.Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("RestaurantPlatform.Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("RestaurantPlatform.Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.Review", b =>
                {
                    b.HasOne("RestaurantPlatform.Domain.Entities.MenuItem", "MenuItem")
                        .WithMany("Reviews")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantPlatform.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.MenuItem", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.RestaurantInfo", b =>
                {
                    b.Navigation("Hours");
                });

            modelBuilder.Entity("RestaurantPlatform.Domain.Entities.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
